sudo: required # needed for trusty beta
dist: trusty   # needed for HarfBuzz

language: c

compiler:
    - gcc
    - clang

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libharfbuzz-dev libfribidi-dev

script:
    - make
    - make check

notifications:
    email:
        recipients:
            - host-oman@googlegroups.com
